// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apiBrigadeiro.Context;

#nullable disable

namespace apiBrigadeiro.Migrations
{
    [DbContext(typeof(apiBrigadeiroContext))]
    [Migration("20230728185240_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("apiBrigadeiro.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereço")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Compras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text");

                    b.Property<int>("Frete")
                        .HasColumnType("integer");

                    b.Property<string>("ListaDoces")
                        .HasColumnType("text");

                    b.Property<int>("ValorTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Doce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComprasId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Quantidades")
                        .HasColumnType("integer");

                    b.Property<string>("Sabores")
                        .HasColumnType("text");

                    b.Property<int>("Valores")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComprasId");

                    b.ToTable("Doces");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Compras", b =>
                {
                    b.HasOne("apiBrigadeiro.Model.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Doce", b =>
                {
                    b.HasOne("apiBrigadeiro.Model.Compras", null)
                        .WithMany("doces")
                        .HasForeignKey("ComprasId");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Compras", b =>
                {
                    b.Navigation("doces");
                });
#pragma warning restore 612, 618
        }
    }
}
