// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apiBrigadeiro.Context;

#nullable disable

namespace apiBrigadeiro.Migrations
{
    [DbContext(typeof(apiBrigadeiroContext))]
    [Migration("20231127130656_AvaliacaoPedidos")]
    partial class AvaliacaoPedidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("apiBrigadeiro.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Endereço")
                        .HasColumnType("text")
                        .HasColumnName("endereço");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Doce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedidoid");

                    b.Property<int>("Quantidades")
                        .HasColumnType("integer")
                        .HasColumnName("quantidades");

                    b.Property<string>("Sabores")
                        .HasColumnType("text")
                        .HasColumnName("sabores");

                    b.Property<int>("Valores")
                        .HasColumnType("integer")
                        .HasColumnName("valores");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("doces");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<int>("Frete")
                        .HasColumnType("integer")
                        .HasColumnName("frete");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedidoid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("entregas");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text")
                        .HasColumnName("formapagamento");

                    b.Property<int>("ValorTotal")
                        .HasColumnType("integer")
                        .HasColumnName("valortotal");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("brigadeiros.Model.Avaliação", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Nota")
                        .HasColumnType("integer")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.ToTable("avaliações");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Doce", b =>
                {
                    b.HasOne("apiBrigadeiro.Model.Pedido", null)
                        .WithMany("doces")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Entrega", b =>
                {
                    b.HasOne("apiBrigadeiro.Model.Pedido", null)
                        .WithMany("entregas")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Pedido", b =>
                {
                    b.HasOne("apiBrigadeiro.Model.Cliente", null)
                        .WithMany("pedidos")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Cliente", b =>
                {
                    b.Navigation("pedidos");
                });

            modelBuilder.Entity("apiBrigadeiro.Model.Pedido", b =>
                {
                    b.Navigation("doces");

                    b.Navigation("entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
